name: Lint (push / PR / schedule)

on:
  push:
    branches: [ main, ramy ]
  pull_request:
    branches: [ main, ramy ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
